# Generated by Django 5.1.2 on 2024-12-12 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPel', models.AutoField(primary_key=True, serialize=False)),
                ('namaDepan', models.CharField(max_length=50)),
                ('namaBlkng', models.CharField(max_length=50)),
                ('alamatPel', models.TextField()),
                ('emailPel', models.EmailField(max_length=254, unique=True)),
                ('tglLahirPel', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sepatu',
            fields=[
                ('idSepatu', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('merek', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NomorTelepon',
            fields=[
                ('idNoTlpPel', models.AutoField(primary_key=True, serialize=False)),
                ('nomorTelepon', models.CharField(max_length=20)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomor_telepon', to='transaksi.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('idPesan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahBarang', models.IntegerField()),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to='transaksi.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('idDetailPesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tglPesan', models.DateField()),
                ('tglPembayaran', models.DateField()),
                ('totalHarga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pesanan', to='transaksi.pesan')),
                ('sepatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pesanan', to='transaksi.sepatu')),
            ],
        ),
    ]
